<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ResolveAssemblyReferencesDependsOn>$(ResolveAssemblyReferencesDependsOn);TransformPackPrivates</ResolveAssemblyReferencesDependsOn>
        <TargetsForTfmSpecificBuildOutput>TransformPackPrivates;$(TargetsForTfmSpecificBuildOutput);IncludeProjectReferenceDlls</TargetsForTfmSpecificBuildOutput>
        <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeReferenceAssemblies</TargetsForTfmSpecificContentInPackage>
        <NoWarn>$(NoWarn);NU5131;DRAGHI001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Slon.Benchmark"/>
        <InternalsVisibleTo Include="Slon.NativeAotSample"/>
        <InternalsVisibleTo Include="Slon.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Draghi/Draghi.Pipelining/Draghi.Pipelining.csproj"/>
    </ItemGroup>

    <Target Name="IncludeProjectReferenceDlls" DependsOnTargets="BuildOnlySettings;ResolveReferences">
        <ItemGroup>
            <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths->WithMetadataValue('ReferenceSourceTarget', 'ProjectReference')->WithMetadataValue('PrivateAssets', 'All'))"
                                  TargetPath="%(ReferenceCopyLocalPaths.DestinationSubDirectory)"/>
        </ItemGroup>
    </Target>

    <!-- Add a ref folder to the package which only exposes the library so that the referenced class library doesn't get exposed. -->
    <Target Name="IncludeReferenceAssemblies">
        <ItemGroup>
            <TfmSpecificPackageFile Include="$(TargetPath)" PackagePath="ref/$(TargetFramework)"/>
        </ItemGroup>
    </Target>
</Project>
